<a href="https://colab.research.google.com/github/sidagarwal-labs/DSBA-6211---Advance-Business-Analytics/blob/main/ANN_(Neural_Network).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#read the data
df=pd.read_csv('HEMQ.csv')

In [ ]:
#Neural network need data completion. So follow imputation or deletion
NA_names= ['MORTDUE', 'VALUE', 'YOJ', 'DEROG',
'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC']
df[NA_names]=df[NA_names].fillna(df[NA_names].mean())

In [ ]:
#categorial variables imputation
df['REASON']=df['REASON'].fillna(df['REASON'].mode()[0])
df['JOB']=df['JOB'].fillna(df['JOB'].mode()[0])

In [ ]:
df.describe(include='all')

BAD          LOAN        MORTDUE          VALUE   REASON  \
count   5960.000000   5960.000000    5960.000000    5960.000000     5960   
unique          NaN           NaN            NaN            NaN        2   
top             NaN           NaN            NaN            NaN  DebtCon   
freq            NaN           NaN            NaN            NaN     4180   
mean       0.199497  18607.969799   73760.817200  101776.048741      NaN   
std        0.399656  11207.480417   42481.395689   56843.931566      NaN   
min        0.000000   1100.000000    2063.000000    8000.000000      NaN   
25%        0.000000  11100.000000   48139.000000   66489.500000      NaN   
50%        0.000000  16300.000000   69529.000000   90000.000000      NaN   
75%        0.000000  23300.000000   88200.250000  119004.750000      NaN   
max        1.000000  89900.000000  399550.000000  855909.000000      NaN   

          JOB          YOJ        DEROG       DELINQ        CLAGE  \
count    5960  5960.000000  5960.000000  5960.000000  5960.000000   
unique      6          NaN          NaN          NaN          NaN   
top     Other          NaN          NaN          NaN          NaN   
freq     2667          NaN          NaN          NaN          NaN   
mean      NaN     8.922268     0.254570     0.449442   179.766275   
std       NaN     7.239301     0.794198     1.071002    83.563059   
min       NaN     0.000000     0.000000     0.000000     0.000000   
25%       NaN     3.000000     0.000000     0.000000   117.371430   
50%       NaN     8.000000     0.000000     0.000000   178.076005   
75%       NaN    12.000000     0.000000     0.449442   227.143058   
max       NaN    41.000000    10.000000    15.000000  1168.233561   

               NINQ         CLNO      DEBTINC  
count   5960.000000  5960.000000  5960.000000  
unique          NaN          NaN          NaN  
top             NaN          NaN          NaN  
freq            NaN          NaN          NaN  
mean       1.186055    21.296096    33.779915  
std        1.653046     9.948280     7.632713  
min        0.000000     0.000000     0.524499  
25%        0.000000    15.000000    30.763159  
50%        1.000000    21.000000    33.779915  
75%        2.000000    26.000000    37.949892  
max       17.000000    71.000000   203.312149

In [ ]:
X=pd.concat([df.iloc[:,1:4],df.iloc[:,6:13]],axis=1)
names=X.columns

In [ ]:
#standardization of variables for neural networks
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X)
X[names]=scaler.transform(X)
X.describe(include='all')

LOAN      MORTDUE        VALUE          YOJ        DEROG  \
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000   
mean      0.197162     0.180378     0.110597     0.217616     0.025457   
std       0.126210     0.106875     0.067040     0.176568     0.079420   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.112613     0.115918     0.068981     0.073171     0.000000   
50%       0.171171     0.169731     0.096708     0.195122     0.000000   
75%       0.250000     0.216705     0.130916     0.292683     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

            DELINQ        CLAGE         NINQ         CLNO      DEBTINC  
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000  
mean      0.029963     0.153879     0.069768     0.299945     0.163991  
std       0.071400     0.071529     0.097238     0.140117     0.037639  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.100469     0.000000     0.211268     0.149115  
50%       0.000000     0.152432     0.058824     0.295775     0.163991  
75%       0.029963     0.194433     0.117647     0.366197     0.184555  
max       1.000000     1.000000     1.000000     1.000000     1.000000

In [ ]:
dummy_data=pd.get_dummies(df[['REASON','JOB']],drop_first=True)
X=pd.concat([X,dummy_data],axis=1)
X.head()

LOAN   MORTDUE     VALUE       YOJ     DEROG    DELINQ     CLAGE  \
0  0.000000  0.059869  0.036590  0.256098  0.000000  0.000000  0.080777   
1  0.002252  0.171050  0.071234  0.170732  0.000000  0.133333  0.104289   
2  0.004505  0.028773  0.010261  0.097561  0.000000  0.000000  0.127942   
3  0.004505  0.180378  0.110597  0.217616  0.025457  0.029963  0.153879   
4  0.006757  0.240856  0.122655  0.073171  0.000000  0.000000  0.079893   

       NINQ      CLNO   DEBTINC  REASON_HomeImp  JOB_Office  JOB_Other  \
0  0.058824  0.126761  0.163991            True       False       True   
1  0.000000  0.197183  0.163991            True       False       True   
2  0.058824  0.140845  0.163991            True       False       True   
3  0.069768  0.299945  0.163991           False       False       True   
4  0.000000  0.197183  0.163991            True        True      False   

   JOB_ProfExe  JOB_Sales  JOB_Self  
0        False      False     False  
1        False      False     False  
2        False      False     False  
3        False      False     False  
4        False      False     False

In [ ]:
y=df['BAD']

In [ ]:
#data partition
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
#build neural network
from sklearn.neural_network import MLPClassifier
ANN = MLPClassifier(hidden_layer_sizes=(5,3),
                    max_iter=300,
                    random_state=0)
ANN.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(5, 3), max_iter=300, random_state=0)

In [ ]:
#coefficients for the first hidden layer
print(ANN.coefs_[0])

[[ 0.28103858 -0.22090395  0.13438464 -0.58981728  0.60087279]
 [-0.75774424  0.41314202  0.36598648  0.59959428  0.59342935]
 [-0.52021398  0.28008493  0.81600953  0.27248735 -0.45345113]
 [-1.1745908  -0.1609805   0.52146756  0.52516202  0.50742086]
 [ 0.40365104 -2.11449602  0.60680116 -1.23888476 -0.24111208]
 [-0.17352575 -0.70559914  1.67029476 -0.57248782 -1.37781095]
 [ 0.46130104  0.49921809 -0.77833896  0.29593093  0.71330258]
 [-1.14022941 -1.47881722  0.66445336  0.53702954 -0.10303958]
 [-0.82810325  0.87101419  0.54286019 -0.45759342  0.44915079]
 [ 0.31016264 -0.90793512  0.87872674 -0.46822197 -0.89356253]
 [ 0.50721621  0.1856795   0.49742268 -0.30295023  0.16521206]
 [-0.14732278  0.39942136  0.08448293 -0.29397314 -0.01118849]
 [-0.64257422 -0.1582892   0.05941426 -0.26468234  0.15165223]
 [-0.10065449  0.40593223  0.33665735  0.22646655 -0.19785045]
 [ 0.56611151 -0.19913074  0.70509684  0.09007763  0.08062421]
 [ 0.32282932  0.23801419  0.28454771 -0.08750689 -0.16

In [ ]:
#coefficients for the 2nd hidden layer. Output of 1st hidden layer = input to 2nd layer
print(ANN.coefs_[1])

[[-2.21835541e+000 -1.02735054e-137 -2.72438223e+000]
 [-1.12479845e+000  2.80525837e-033 -1.60127282e+000]
 [ 8.77206377e-001 -4.48839273e-042  1.10843583e+000]
 [-9.06239477e-001  4.38948057e-053 -1.28188806e-001]
 [-1.59547759e+000  1.39069374e-049 -1.73054696e+000]]


In [ ]:
#coefficients of the output layer. Output of 2nd hidden layer = input of last year
print(ANN.coefs_[2])

[[2.18602757e+00]
 [5.04482670e-45]
 [9.88189231e-01]]


In [ ]:
#compare the model to the validation set
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve
prediction=ANN.predict(X_val)
confusion_matrix(y_val,prediction)

array([[1391,   53],
       [ 229,  115]])

In [ ]:
ANN.score(X_val,y_val)

0.8422818791946308

In [ ]:
prediction_prob=ANN.predict_proba(X_val)
roc_auc_score(y_val,prediction_prob[:,1])

np.float64(0.8048540874830895)

In [ ]:
from sklearn.inspection import permutation_importance

perm = permutation_importance(ANN,
                              X_val,
                              y_val,
                              n_repeats=30,
                              random_state=0,
                              scoring='roc_auc')

In [ ]:
perm_series = pd.Series(data=perm.importances_mean,
                        index=X_val.columns.values).sort_values(ascending=False)
display(perm_series.head(15))

DELINQ            0.084431
DEROG             0.048652
CLAGE             0.038701
NINQ              0.031829
DEBTINC           0.021313
CLNO              0.019129
MORTDUE           0.016841
REASON_HomeImp    0.012177
LOAN              0.010284
JOB_Office        0.010237
YOJ               0.008359
JOB_Other         0.007944
VALUE             0.007711
JOB_Sales         0.005375
JOB_ProfExe       0.004379
dtype: float64